### ISSUE TITLE
System can not find liboffloadhal.so

### ISSUE THREAD

**Issue by Roker2** [zeelog/android_device_xiaomi_mido#12]
F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/ipacm": library "liboffloadhal.so" not found

**Comment by Roker2** [comment]
https://github.com/CarbonROM/android_device_xiaomi_mido/commit/f20ecd87c91658e8cfb4f4ad53a6dfe61aff4910

**Comment by zeelog** [comment]
not related with this device tree
