### ISSUE TITLE
proprietary-files-qc.txt is not updated

### ISSUE THREAD

**Issue by Roker2** [zeelog/android_device_xiaomi_mido#20]
You need to update file in accordance with [this commit](https://github.com/zeelog/proprietary_vendor_xiaomi/commit/33d7915b626700090378e7bab748fe938e2e2219) 
[Fix](https://github.com/AOSiP-Devices/device_xiaomi_mido/commit/ca3d66c8ece9a1e2aa6afd8e1ec0e6023e525ca9)

**Comment by zeelog** [comment]
it's updated now :)
