### ISSUE TITLE
No way guard for errors like "already defined"

### ISSUE THREAD

**Issue by Roker2** [zeelog/android_device_xiaomi_mido#79]
Example:
build/make/core/base_rules.mk:325: error: device/leeco/s2/rro_overlays/CarrierConfigOverlay: MODULE.TARGET.ETC.CarrierConfigOverlay already defined by device/xiaomi/mido/rro_overlays/CarrierConfigOverlay.

Fix:
https://github.com/GiaSen/android_device_xiaomi_mido/commit/935dfaeace4a0c54de6dddb99156adf43d79915f

**Comment by GiaSen** [comment]
Yeah I had same issue when building different device, happy you found my commit
